---
name: YAML Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lintFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Run yamllint
        uses: frenck/action-yamllint
        with:
          config: ".github/.yamllint"
